/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:74815bc3-6394-465b-96f0-57e93fa902ff",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_cYmSXsgHO",
    "aws_user_pools_web_client_id": "3eia8vu2kfjs4dpkbusg9f8kb",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://cuvrxw4dubfjbld4e7jldeuvci.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-gzvzs2teubg2vddyzyjyfya3cm",
    "aws_user_files_s3_bucket": "usernm131046-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
